name: CI/CD Deploy

on:
  push:
    branches:
      - hw6

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy code to server
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "БР2/Мельник_Софья/homeworks/hw6/microservices/*"
        target: "~/microservices/microservices"

    - name: Run Docker Compose on server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd ~/microservices/microservices
          docker-compose down
          docker-compose up -d --build
